V7 merge
aldeed/meteor-autoform pull request #1693
Opened 2020-03-30 14:10 UTC by pouya-eghbali

Merge pouya-eghbali/meteor-autoform

2020-05-13 08:13 UTC, jankapunkt commented
So I cloned this and built it into my staging environment after locally were no issues. Our staging users reported no issues with it yet, so it seems to be a good fit :+1: 

The only issues so far are from my end:

* we need to update the documentation
* we need to show how to add Bootstrap 4 templates, mainly because the `imajus:autoform-bootstrap4` is relying on some Template helpers from the Bootstrap3 templates, and I had to create an own package that fixes the (`jkuester:autoform-bootstrap4`)
* we should at least add some unit tests for functions that don't require templating, puppeteer etc. for now (later we may extend this)
* I have tested some of my extensions and they all worked, however the most popular extensions need to be tested, too
* The extensions list may be curated in order to remove abandoned packages or get them into the community if they are very popular

I would offer to review the documentation but the @Meteor-Community-Packages/autoforms team may clone this and try it out locally, too.

2020-05-14 16:32 UTC, pouya-eghbali commented
@jankapunkt sorry I'm really really busy these days with everything going remote, I don't know when I can help, maybe in two weeks, but do tell me if you find any issues. Personally I didn't have any issues on my dev machine, staging and on production so far and I don't have any updates for this PR for now.

2020-06-09 09:02 UTC, jankapunkt requested changes
I finally managed to make a full review of the code. There are minor issues but they are spread accross the code. I would mostly care about the following

**code**

- `isObject` has a truthy return value also for arrays and functions which makes it hard to debug any condition because we never know, whether `isObject` was true, due to a value being an object, array or function. It caused no runtime errors for me but future debugging sessions could be more exhausting due to this unknown state
- avoid `var` wherever possible and use `const` for all non-redeclarable variables, otherwise `let`
- use template literals instead of manually concatenating Strings
- replace `indexOf(...) > -1` and similar with `.includes` where the index itself is not of interest (but not with `lastIndexOf` which can't be replaces by `includes`)
- Rename single-char variables to something more understandable
- sometimes the multiline formatting (especially function paramters) can make it harder to read but this is maybe also a personal thing of me


**documenation**

- Add some short summary on undocumented methods of any class / higher Object
- Make notes on new or altered behavior
- Make notes (if possible) if new / altered behavior fixes a related issue
- Update `API.md`

**consequences of changes** 

The most changes may not have consequences, however

- if a `var` declared variable was beforehand not block-scoped and the code unintentionally assumed this variable to be global or not block-scoped this could lead to an error. However it is then not the fault of the variable being declared as `const` or `let` but because of wrong scoping and the scoping should be fixed, rather than leaving the variable as `var`
- the `isObject` currently represents also a truthy state for array and function values but should not do this. instead each case should tested separately. This may cause errors on conditions, that implicitly expect a value to bei either an object, array or function (and where `isObject` is currently in correct use).

Both should be handled with care and tested thoroughly.

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +    AutoForm._destroyForm[formId] || new ReactiveVar(false);
I wonder if this formatting is easier to read than the line above.

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +) {
Same here. I think this makes sense when there are many parameters, but with two parameters it seems to be even harder to read than the one-liner.

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +    );
Can't we use [template-literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) here? I think we should use template-literals for any string concatenation.

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +) {
Also too much to break for one char, IMO

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +) {
This for example makes total sense to me to break, this much more readable than in one line

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +    return templateType + "_" + schemaAutoFormDefs[templateType].template;
Can we use template-literals here?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +    return templateType + "_" + schemaAutoFormDefs.template;
Can we use template-literals here?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +    return templateType + "_" + templateFromAncestor;
Can we use template-literals here?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +    return templateType + "_" + templateFromAncestor;
Can we use template-literals here?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +    return templateType + "_" + defaultTemplateForType;
Can we use template-literals here?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +    return templateType + "_" + defaultTemplate;
Can we use template-literals here?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +    }
Is this new behavior added to the documentation already?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
>      updateDoc = AutoForm.Utility.docToModifier(doc, {
I question to this - does it make sense to add a flag, that prevents returning one of `insertDoc` or `updateDoc`? I think it is not necessary to generate both all the time, since each form serves one purpose. To be backward compatible this could be done by checking explicit `false` and otherwise by default return both, as it already does. wdyt?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> + */
Is this updated in the API.md already?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +    const { ancestors } = fieldName
Maybe adding a comment here about the structure of `ancestors`, that is about to be processed?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +          parent = parent ? parent + "." + sub : sub;
Can we use template-literals here?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +      .reduce(
Also please a short comment on the reduce function, I think they are often the hardest to understand when their behavior is not described

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +    for (ancestor of ancestors) {
Shouldn't we define for loop variables either using `let` or `const`?

```javascript
 for (const ancestor of ancestors) { ... }
```
Is there a reason to not use `ancestors.forEach` here?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> + * @param {Boolean} [clean] Indicates if the method should clean the values or not. Default is true.
May it be, that we wll have more options parameters here in the future? If so, it would make sense to make the third parameter an Object to allow non-breaking adds of arbitrary options:

```javascript
 function autoFormGetFieldValue(fieldName, formId, { clean = true } = {}) { ... }
```

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +) {
Is the new paramter structure added to API.md?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +};
Could you please add some method-internal comments on how `isMarkedChanged` is introducing new behavior to this mathod?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +AutoForm.setFieldValue = function autoFormSetFieldValue(
Is this already added to API.md?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +  const keyExists = Boolean(mDoc.getInfoForKey(fieldName));
Are `mDoc` and  `getInfoForKey` things, that are definitely always present or should we check like

```javascript
const keyExists = Boolean(mDoc && mDoc.getInfoForKey && mDoc.getInfoForKey(fieldName));
```

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +AutoForm.setFormValues = function autoFormSetFormValues(value, formId) {
Is this added to `API.md`?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +  element
This could remain in one line IMO

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +  ) {
We could also use `view.name.includes(someString)` -> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
>  };
Maybe use `view.name.includes`?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +    def => def.template == inputTypeTemplate
We should use always compare using  `===` instead of `==` since `==` can produce many false-positives/false-negatives

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +    formType = form.type;
We should use always `const` or `let` since `var` cannot define variables in [block-scope](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let).

Also for readability it may be good to define each variable in a separate line like

```javascript
const form = AutoForm.getCurrentDataForForm(formId);
const formType = form.type;
let formDoc = undefined;

...
```

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +  while (val === undefined && view && view.name !== "Template.autoForm") {
If we often check against the same String, it makes sense to create a short helper

```javascript
const isAutoFormTemplate = view => view && view.name === "Template.autoForm";
```

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +    searchObj;
Please let's define variables as either `let` or `const`, also this makes the code more verbose to understand roles of the variables.

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
>          }
Alternative suggestion:

```javascript
Object.entries(searchObj).forEach(function([key, value]) {
  if (key.includes(prefix)) {
    const suffix = key.slice(prefix.length)
    result[suffix] = value;
  }
```

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +  while (view && view.name !== "Template.autoForm") {
Could use the helper I added some comments before

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +  if (view && view.name === "Template.autoForm") {
Could use the helper I added some comments before

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> -      console.log('Error in ' + this.formId, operation, error);
Let's use template literals here

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +  while (view && view.name !== "Template.autoForm") {
Could use the helper I defined in some comments before

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +  if (!view || view.name !== "Template.autoForm") {
Could use the helper I defined in some comments before

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +  data = { ...data };
Maybe adding a short comment on why using the Object-spread and not `Object.assign` here

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +    fields;
Please let's use `let` and `const` for more verbosity of the code

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
>        var f = $(this);
can `f` be renamed? One-char variables make the code really hard to read IMO

2020-06-09 09:02 UTC, jankapunkt commented on autoform-api.js
> +      stickyErrors = Object.entries(stickyErrors).map(function([k, obj]) {
can we make `k` to `key`?

2020-06-09 09:02 UTC, jankapunkt commented on common.js
> +}
Please add a new line at the end of the file

2020-06-09 09:02 UTC, jankapunkt commented on common.js
> +export const isObject = obj => toString.call(obj) == '[object Object]' || Array.isArray(obj) || isFunction(obj)
Shouldn't `isObject` return false if it's an array or a function?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-arrays.js
> +    childKeys = ss.objectKeys(AutoForm.Utility.makeKeyGeneric(field) + ".$");
Can we use template literals to concat Strings?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-arrays.js
> +  self.info[formId][field].collection = collection;
Can we be sure that there is always the ability to access these arrays without error?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-arrays.js
> +ArrayTracker.prototype.getMinMax = function atGetMinMax(
Please add a short jsDoc comment what this method does.

2020-06-09 09:02 UTC, jankapunkt commented on autoform-arrays.js
> +ArrayTracker.prototype.initField = function atInitField(
Please add a short jsDoc comment what this method does.

2020-06-09 09:02 UTC, jankapunkt commented on autoform-arrays.js
>  ArrayTracker.prototype.resetForm = function atResetForm(formId) {
Please add a short jsDoc comment what this method does.

2020-06-09 09:02 UTC, jankapunkt commented on autoform-arrays.js
>  ArrayTracker.prototype.untrackForm = function atUntrackForm(formId) {
Please add a short jsDoc comment what this method does.

2020-06-09 09:02 UTC, jankapunkt commented on autoform-arrays.js
> +ArrayTracker.prototype.getVisibleCount = function atGetVisibleCount(
Please add a short jsDoc comment what this method does.

2020-06-09 09:02 UTC, jankapunkt commented on autoform-arrays.js
> +ArrayTracker.prototype.isFirstFieldlVisible = function atIsFirstFieldlVisible(
Please add a short jsDoc comment what this method does.

2020-06-09 09:02 UTC, jankapunkt commented on autoform-arrays.js
> +ArrayTracker.prototype.isLastFieldlVisible = function atIsLastFieldlVisible(
Please add a short jsDoc comment what this method does.

2020-06-09 09:02 UTC, jankapunkt commented on autoform-arrays.js
> -ArrayTracker.prototype.addOneToField = function atAddOneToField(formId, field, ss, overrideMinCount, overrideMaxCount) {
Please add a short jsDoc comment what this method does.

2020-06-09 09:02 UTC, jankapunkt commented on autoform-arrays.js
> +    }
Can we use template literals to concat strings?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-arrays.js
>      var i = self.info[formId][field].array.length;
please use `let` or `const` because `var`is not block scoped here. Coould we also rename `i` to something more verbose?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-arrays.js
> +  var minCount = self.getMinMax(ss, field, overrideMinCount, overrideMaxCount)
Please use `let` or `const` for variables

2020-06-09 09:02 UTC, jankapunkt commented on autoform-arrays.js
> +    .minCount;
Could also be written as

```javascript
const { minCount } = self.getMinMax(...)
```

2020-06-09 09:02 UTC, jankapunkt commented on autoform-arrays.js
>    };
Can we use template literals to concat strings and avoid `var`?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-arrays.js
>      });
Can we use template literals and write `k` as `key`?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-formdata.js
> +FormData = function() {
does it make sense to rewrite this as an es6 class? 

```javascript
FormData = class FormData { ... }
```

2020-06-09 09:02 UTC, jankapunkt commented on autoform-helpers.js
>  });
There should be a round bracket around:

```
...
|| (options.values && options.values.split().filter() )
```

and indentation is 2 spaces too far right

2020-06-09 09:02 UTC, jankapunkt commented on autoform-helpers.js
>          return (field.slice(-2) !== '.$' && field.indexOf('.$.') === -1);
Maybe use `&& !field.includes('.$.')`?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-helpers.js
> +        return true; // keep
Is there a related issue that has been fixed due to this?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-helpers.js
>        var lastDotPos = field.lastIndexOf('.');
Please use `const`

2020-06-09 09:02 UTC, jankapunkt commented on autoform-helpers.js
> +      return !fieldList.includes(parentField) || parentField === name || parentField === genericName
Does this change fix an issue? Please add as comment if so

2020-06-09 09:02 UTC, jankapunkt commented on autoform-helpers.js
>          return name + '.' + field;
Can we use template-literals here?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-helpers.js
> +    if (fieldDefs.autoform && isFunction(fieldDefs.autoform.omit) && fieldDefs.autoform.omit(field) === true) {
Can you please add a comment if this new introduced behavior? Also - does it fix an issue? If so, please comment, too.

2020-06-09 09:02 UTC, jankapunkt commented on autoform-helpers.js
> +  fieldList = fieldList.filter(function shouldIncludeField(field) {
If `fieldList` is reassigned, it should be declared using `let`

2020-06-09 09:02 UTC, jankapunkt commented on autoform-helpers.js
>      var fieldDefs = AutoForm.Utility.getFieldDefinition(ss, field);
Please avoid `var`

2020-06-09 09:02 UTC, jankapunkt commented on autoform-helpers.js
> +  var atts = 'value' in this ? { value: this.value } : {}
Please avoid `var`

2020-06-09 09:02 UTC, jankapunkt commented on components/afFormGroup/afFormGroup.html
> +</template>
Please add a newline add the end of the file

2020-06-09 09:02 UTC, jankapunkt commented on components/afFormGroup/afFormGroup.js
> +    var c = AutoForm.Utility.getComponentContext(this, "afFormGroup");
Can we rename `c` to `context` or `ctx`?
Please avoid `var`.

2020-06-09 09:02 UTC, jankapunkt commented on components/afFormGroup/afFormGroup.js
> +    var id = instance.fieldIds[name];
Please avoid `var`

2020-06-09 09:02 UTC, jankapunkt commented on components/afFormGroup/afFormGroup.js
> +        id = idPrefix + "-" + id;
Ca we use template literals?

2020-06-09 09:02 UTC, jankapunkt commented on components/afFormGroup/afFormGroup.js
> +      key.indexOf("formgroup-") !== 0
Can we use `includes` instead of `indexOf`?

2020-06-09 09:02 UTC, jankapunkt commented on components/autoForm/autoForm.js
>      var removeProps = [
Avoid `var`

2020-06-09 09:02 UTC, jankapunkt commented on components/autoForm/autoForm.js
> +        return prop.indexOf(componentType + "-") === 0;
Prefer `includes`

2020-06-09 09:02 UTC, jankapunkt commented on components/autoForm/autoForm.js
> +              "Oops! Did you forget to return the modified document from your docToForm hook for the " +
Can we use template literals?

2020-06-09 09:02 UTC, jankapunkt commented on components/quickForm/quickForm.js
> +  fields = fields.filter(f => ![null, undefined, ''].includes(f));
We can declare `f => ![null, undefined, ''].includes(f)` outside of the functions as it's re-used a lot in more than one method:

```
const emptyVals = [null, undefined, '']
const emptyFields = field => !emptyVals.includes(field)
```

and later use it like

```
fields = fields.filter(emptyFields);
```

2020-06-09 09:02 UTC, jankapunkt commented on formTypes/update-pushArray.js
> +        collection.update({ _id: c.docId }, modifer, c.validationOptions, c.result);
Can we rename `c`?

2020-06-09 09:02 UTC, jankapunkt commented on formTypes/normal.js
>        var result = hook.call(ctx, c.insertDoc, c.updateDoc, c.currentDoc);
Can we rename `c`?

2020-06-09 09:02 UTC, jankapunkt commented on formTypes/update.js
> +        collection.update({ _id: c.docId }, modifier, c.validationOptions, c.result);
Can we rename `c`?

2020-06-09 09:02 UTC, jankapunkt commented on versions.json
> +}
Please add a newline at the end

2020-06-09 09:02 UTC, jankapunkt commented on utility.js
> +          val = val.filter(v => ![null, undefined, ''].includes(v));
Oh we can even make `v => ![null, undefined, ''].includes(v)` a common function as it's even used accross modules.

2020-06-09 09:02 UTC, jankapunkt commented on utility.js
>            label = v.charAt(0).toUpperCase() + v.slice(1).toLowerCase();
Can we use template literals?

2020-06-09 09:02 UTC, jankapunkt commented on utility.js
>        for (var i = 0; i < subkeylen; i++) {
Since for loop with `break` are basically abstracted `goto` we should use a `forEach` alternative with `return`:

```javascript
const loop = [];
const loop.length = subkeylen;
loop.forEach((subkey, index) => {
  if (typeof current[subkey] !== 'undefined' && !isObject(current[subkey])) {
    return; // already set for some reason; leave it alone
  }

  if (index === subkeylen - 1) {
    ...
  }
})
```

2020-06-09 09:02 UTC, jankapunkt commented on utility.js
> +          obj[key] = val.filter(item => ![void 0, null].includes(item));
`item => ![void 0, null].includes(item)` could be extracted into a module-level function

2020-06-09 09:02 UTC, jankapunkt commented on utility.js
> +        } else if (!(val instanceof Date) && isObject(val)) {
This is an example, where `isObject` is confusing - since it returns true also if val is an array or a function I would not know, whether the if condition will at this point be true because val is an object, an array or a function.

2020-06-09 09:02 UTC, jankapunkt commented on utility.js
>  if (typeof Object.getPrototypeOf !== 'function') {
Is this obselete due to `web.legacy`?

2020-06-09 09:02 UTC, jankapunkt commented on utility.js
> +var isBasicObject = function (obj) {
Please avoid `var`

2020-06-09 09:02 UTC, jankapunkt commented on autoform-events.js
> +  if (gKey.slice(-2) === ".$" || gKey.indexOf(".$.") !== -1) {
Use `includes`

2020-06-09 09:02 UTC, jankapunkt commented on autoform-events.js
> +    key = gKey.slice(0, gKey.indexOf(".$"));
Can we use template literals here?

2020-06-09 09:02 UTC, jankapunkt commented on autoform-events.js
> +    if ([13, 9, 16, 20, 17, 91, 37, 38, 39, 40].includes(event.keyCode)) return;
This array can be declared as const on the module level

2020-06-09 09:02 UTC, jankapunkt commented on autoform-inputs.js
> +    var fieldName,
Please avoid `var`

2020-06-09 09:02 UTC, jankapunkt commented on autoform-inputs.js
> +  var dotPos = fieldName.lastIndexOf(".");
Please avoid `var`

2020-06-09 09:02 UTC, jankapunkt commented on components/afFieldInput/afFieldInput.js
> +  var c = AutoForm.Utility.getComponentContext(this, "afFieldInput");
Please avoid var and rename `c` to something more verbose

2020-06-09 09:02 UTC, jankapunkt commented on components/afFieldInput/afFieldInput.js
> +export function afFieldInputContext() {
Please comment on the function with a short summary

2020-06-09 09:02 UTC, jankapunkt commented on components/afFieldInput/afFieldInput.js
> +    if (templateName.indexOf("_plain") !== -1) {
Please use `includes`

2020-06-09 09:02 UTC, jankapunkt commented on formTypes/method-update.js
>      var c = this;
Please avoid `var` and rename `c` to something understandable

2020-06-09 09:02 UTC, jankapunkt commented on formTypes/method-update.js
> +      var valid =
Please avoid `var`

2020-06-09 09:02 UTC, jankapunkt commented on formTypes/method-update.js
>          var ddp = c.formAttributes.ddp;
Please avoid `var`

2020-06-09 09:02 UTC, jankapunkt commented on formTypes/method-update.js
>      var ss = AutoForm.getFormSchema(this.form.id);
Please avoid `var`

2020-06-09 09:02 UTC, jankapunkt commented on formTypes/method.js
>      var c = this;
Please avoid `var` and rename `c`

2020-06-09 09:02 UTC, jankapunkt commented on formTypes/method.js
> +      var valid =
Please avoid `var`

2020-06-09 09:02 UTC, jankapunkt commented on formTypes/method.js
>          var ddp = c.formAttributes.ddp;
Please avoid `var`

2020-06-09 09:02 UTC, jankapunkt commented on formTypes/method.js
>      var collection = AutoForm.getFormCollection(this.form.id);
Please avoid `var`

2020-06-09 09:19 UTC, pouya-eghbali commented
The `var`,`indexOf` and single char / short names are not my doings, I tried to use `const` whenever I rewrote any part of this, and if that wasn't possible I used `let`, I tried my best not to touch the original code but if we're doing a major update we should replace all these and move to >es6.

For the breaking of parameters and formatting, I used [prettier](prettier.io) with default settings, we can decide on a linter and add a config file to automatically format the code. I used prettier with default settings because that's what I use for all my projects.

All changes I made are somehow documented in the new readme, this was fine for a fork, but we need to move it to the documentation. Regarding the `isObject` function, do you know a standalone fast implementation?

2020-06-09 09:23 UTC, pouya-eghbali commented
For `isObject` the current implementation is

```javascript
export const isObject = obj => toString.call(obj) == '[object Object]' || Array.isArray(obj) || isFunction(obj)
```

can't remember the reason behind this, we should check if removing ` || Array.isArray(obj) || isFunction(obj)` won't break any functionality, or if it does then it should be replaced with an appropriate function call where it breaks.

2020-06-09 14:01 UTC, jankapunkt commented
> The var,indexOf and single char / short names are not my doings, I tried to use const whenever I rewrote any part of this, and if that wasn't possible I used let, I tried my best not to touch the original code but if we're doing a major update we should replace all these and move to >es6.
>
> For the breaking of parameters and formatting, I used prettier with default settings, we can decide on a linter and add a config file to automatically format the code. I used prettier with default settings because that's what I use for all my projects.

I see, I was already curious because at some parts there wire mixed `var` and `const`. I think prettier is a stable and well established tool and we could go for it. I could setup some github action / ci using it to lint-test any pushes and pull requests (will create a PR for that).

If you give me access to the dev repo I can take over that part with the ES6 and fix all my mentioned things in the review. An alternative would be to merge this into a `v7.x` branch instead of `devel` and work from here towards a stable v7. What do you think?

> can't remember the reason behind this, we should check if removing || Array.isArray(obj) || isFunction(obj) won't break any functionality, or if it does then it should be replaced with an appropriate function call where it breaks.

I think the function should not be too complicated and fulfill the following requirements:

- check if it's not an Array
- check if it's not a Function

I checked the [polyfill for `Array.isArray`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#Polyfill) and would do

```javascript
export const isObject = obj => Object.prototype.toString.call(obj) === '[object Object]'
```

which is basically the explicit version of `toString.call(obj) == '[object Object]'` and in any situation it breaks there should be an extra condition with `else if (Array.isArray(obj)) { ... }` and/or `else if (typeof obj === 'function') { ... }```

2020-06-16 06:36 UTC, jankapunkt commented
I just want to ask again, do you think it's a good idea to merge this to a `v7` branch instead of `develop` so I can immediately fix the issues that are left and we can soon merge? When I am through I will ask for at least one reviewer from the team and then we should soon be able to merge.

2020-06-18 14:06 UTC, pouya-eghbali commented
Yeah, let's do that. That sounds like a better idea.

2020-06-18 15:09 UTC, jankapunkt commented
Allright, changed the base branch and will implement the mentioned issues, I hope this will be done this weekend :-)

2020-06-18 15:12 UTC, merged